name: resume.json gist

on:
  push:
    branches: ["master"]
    paths: ["resume.json"]
  pull_request:
    branches: ["master"]
    paths: ["resume.json"]
  workflow_dispatch:

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: c7b59ab6604fd86bbc792c2fab24029c
          file_path: resume.json
