name: t2006 deploy

on:
  push:
    branches: ["master"]
    paths:
      - "data.json"
      - "style.json"
      - "img/**"
      - "fonts/**"
  pull_request:
    branches: ["master"]
    paths:
      - "data.json"
      - "style.json"
      - "img/**"
      - "fonts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install -g t2006
      - run: t2006 --input '.' --output '.'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
